
SELECT LAST, FIRST
FROM OFFICERS JOIN CRIME_OFFICERS USING (OFFICER_ID)
JOIN CRIMES USING (CRIME_ID)

GROUP BY LAST, FIRST 
HAVING COUNT (CRIME_ID) < (SELECT MAX(COUNT(CRIME_ID))

FROM CRIMES JOIN CRIME_OFFICERS USING (CRIME_ID)
GROUP BY OFFICER_ID);

SELECT LAST, FIRST 
FROM CRIMiNALS JOIN CRIMES USING (CRIMINAL_ID)
WHERE V_STATUS = 'N'
GROUP BY FIRST, LAST 
HAVING COUNT (CRIME_ID) > (SELECT AVG(COUNT(CRIME_ID))
FROM CRIMES GROUP BY CRIMINAL_ID);

SELECT * FROM APPEALS
WHERE HEARING_DATE - FILING_DATE < ALL (SELECT AVG(HEARING_DATE - FILING_DATE)
FROM APPEALS);

SELECT LAST, FIRST
FROM PROB_OFFICERS JOIN SENTENCES USING(PROB_ID)
GROUP BY FIRST, LAST
HAVING COUNT (CRIMINAL_ID) > (SELECT AVG(COUNT(CRIMINAL_ID))
FROM SENTENCES
GROUP BY PROB_ID);

SELECT CRIME_ID, COUNT(APPEAL_ID)
FROM APPEALS
GROUP BY CRIME_ID
HAVING COUNT(APPEAL_ID) = (SELECT MIN(COUNT(APPEAL_ID))
FROM APPEALS
GROUP BY CRIME_ID);